version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: icu_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: icu_user
      POSTGRES_PASSWORD: icu_password
      POSTGRES_DB: icu_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: